### ISSUE TITLE
Inertia support

### ISSUE THREAD

**Issue by d8vjork** [laravel-arcanist/arcanist#16] opened 2021-07-16 09:15 UTC
Hi there, I see this package very useful for something my company is trying to do

Also we're using InertiaJS, it will be very nice to have compatibility with this package like the "Custom renderers" (which seems wip in the docs page) and sharing data will be much easier reusing Inertia's methods.

**Comment by d8vjork** [comment] 2021-07-16 09:43
Ok I was too quick, actually I found the inertia response adapter you guys created on a different repo, now what's left is a little usage guide

**Comment by jonagoldman** [comment] 2021-07-20 08:30
I think the [single file package](https://github.com/laravel-arcanist/inertia-response-renderer) should be included in the main repo. Only 1 file, no need to make it a separate composer package to add to the list.

**Comment by d8vjork** [comment] 2021-07-20 08:32
Indeed, PHP is not like JS, don't need to cut down in size as long as its only used when the user is using Inertia in his Laravel setup

**Comment by ksassnowski** [comment] 2021-07-20 08:45
The issue is not the source files but the additional dependencies that the Inertia renderer has. Pulling it into the main package would mean that every project that installs Arcanist now automatically also depends on Inertia.

**Comment by jonagoldman** [comment] 2021-07-20 08:57
More here https://github.com/laravel-arcanist/inertia-response-renderer/issues/5

**Comment by jonagoldman** [comment] 2021-07-20 09:02
Oh I see the problem now, but having a separate package also have some [issues](https://github.com/laravel-arcanist/inertia-response-renderer/issues/5):

- its not configurable (can't use main config file to e.g. change Inertia pages path, change route names, ...)
- its one more composer dependency.
- its one more Service Provider that needs to be loaded.

**Comment by d8vjork** [comment] 2021-07-20 09:04
Why not use Laravel's container instead of depending from the package itself?

I see this used in some packages, they also add the dependency as suggested instead of a requirement

**Comment by ksassnowski** [comment] 2021-07-21 11:08
The `suggets` idea is an interesting suggestion. I will have a look at how Laravel deals with this internally e.g. for its various cache drivers. 

I'm going to close this issue for now since Arcanist _does_ support Inertia.js (in fact, that was my primary use-case when writing the package) and the conversation got a bit derailed. I saw that you also opened an issue in the `inertia-response-renderer` package regarding merging it into the core package, so let's continue the conversation there.

**Closed by ksassnowski** 2021-07-21 11:08 UTC
